### ISSUE TITLE
Where are all the Dockerfile sources?

### ISSUE THREAD

**Issue by andreujuanc** [devcontainers/templates#72] opened 2022-12-03 15:44 UTC
Somehow all templates now point to a dockerhub hosted image, but I cannot find the actual sources anymore.

**Comment by samruddhikhandale** [comment] 2022-12-05 16:50
Duplicate of https://github.com/devcontainers/spec/issues/145

> Recently, we have modified the "Add devcontainer configuration files" command to make it more simpler and easier to understand. We have updated the [Templates](https://github.com/devcontainers/templates) and built the dev container config using [Features](https://github.com/devcontainers/features) (which avoids the need of `Dockerfile` in most cases).
>
> We still have few Templates which consist of a Dockerfile (eg. [cpp](https://github.com/devcontainers/templates/tree/main/src/cpp/.devcontainer), [anaconda](https://github.com/devcontainers/templates/tree/main/src/anaconda/.devcontainer))
>
> ℹ️  Look how the `java` Template got simplified which looks more clean and utilizes the Features - [old config](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/java/.devcontainer) vs [new config](https://github.com/devcontainers/templates/tree/main/src/java/.devcontainer).

**Comment by samruddhikhandale** [comment] 2022-12-05 23:35
Closing as duplicate !

**Closed by samruddhikhandale** 2022-12-05 23:35 UTC

**Comment by andreujuanc** [comment] 2022-12-05 23:43
Mine was more related to the source itself here in the repo, but ok.

**Comment by Chuxel** [comment] 2022-12-06 00:06
@andreujuanc Source code for the images themselves are at https://github.com/devcontainers/images
